### ISSUE TITLE
Question about the saga? 

### ISSUE THREAD

**Issue by RomanCharnashei** [mauroservienti/welcome-to-the-state-machine-demos#185]
Hello Mauro, could you clarify me your vision of saga ? Do I understand correctly that saga has no single spot of orchestration and it is adistributed process between services. In other words, can it be called choreography ?
And as far as I understood that you do not admit orchestration-based saga, right ?

**Comment by mauroservienti** [comment]
@RomanCharnashei thanks for your question. I'm writing a blog post on the topic, should be published in a couple of weeks.

In essence, if it solves the problem everything works for me 😃. It mostly depends on the level of coupling we can/are willing to accept.

That being said, a choreography kind of approach is the one I prefer. It elegantly solves the problem, it's simple in all its composing parts (policies). Accompanied with [ViewModel Composition](https://milestone.topics.it/categories/view-model-composition) techniques and a [predictive ViewModel](https://milestone.topics.it/2021/06/02/can-we-predict-the-future.html) approach when needed comes with little to no side effects.

What do you think?

**Comment by RomanCharnashei** [comment]
@mauroservienti Thank you a lot for your efforts and for sharing your knowledge. I will look forward to your article. 
About my thoughts, I haven't worked that much with saga yet and when i first learned about choreography I really thought this thing is brilliant in its simplicity but it seems to me when the documentation on the project is in a bad state or not at all then code readability comes into play and in this case, orchestration can help out.
Also it seems to me orchestration + state machine can help with intersecting requests for example, when a request is being processed but they want to cancel it or editing with adding and removing steps in the saga (but it is my guess). But again it's depend... .
By the way ViewModel Composition cool series of articles, I am imbued. Thank you.

**Comment by mauroservienti** [comment]
> @mauroservienti Thank you a lot for your efforts and for sharing your knowledge. I will look forward to your article. 

My pleasure.

> Also it seems to me orchestration + state machine can help with intersecting requests for example, when a request is being processed but they want to cancel it or editing with adding and removing steps in the saga (but it is my guess). But again it's depend...

Can you expand a bit on this?

> By the way ViewModel Composition cool series of articles, I am imbued. Thank you.

Thank you ☺️

**Comment by RomanCharnashei** [comment]
> 
> 
> @RomanCharnashei if you're interested a blog post preview, under review, is available at [mauroservienti/milestone.github.io#245](https://github.com/mauroservienti/milestone.github.io/pull/245)

Thanks a lot. Of course, I'm very interested.  )
Regarding expand a bit, I have not yet been able to find a good example to explain the idea. I will try to make it.
